import Img1 from "./assets/images/rasm1.svg";
export const foods = [
  {
    id: 0,
    img: Img1,
    title: "Spicy seasoned seafood noodles",
    price: "2.29",
    description: "20 Bowls available",
  },
  {
    id: 1,
    img: Img1,
    title: "Salted Pasta with mushroom sauce",
    price: "2.69",
    description: "11 Bowls available",
  },
  {
    id: 2,
    img: Img1,
    title: "Beef dumpling in hot and sour soup",
    price: "2.99",
    description: "16 Bowls available",
  },
  {
    id: 3,
    img: Img1,
    title: "Healthy noodle with spinach leaf",
    price: "3.29",
    description: "22 Bowls available",
  },
  {
    id: 4,
    img: Img1,
    title: "Hot spicy fried rice with omelet",
    price: "3.49",
    description: "13 Bowls available",
  },
  {
    id: 5,
    img: Img1,
    title: "Spicy instant noodle with special omelette",
    price: "3.59",
    description: "17 Bowls available",
  },
  {
    id: 6,
    img: Img1,
    title: "Spicy seasoned seafood noodles",
    price: "2.29",
    description: "20 Bowls available",
  },
  {
    id: 7,
    img: Img1,
    title: "Spicy seasoned seafood noodles",
    price: "2.29",
    description: "20 Bowls available",
  },
  {
    id: 8,
    img: Img1,
    title: "Spicy seasoned seafood noodles",
    price: "2.29",
    description: "20 Bowls available",
  },
  {
    id: 9,
    img: Img1,
    title: "Spicy seasoned seafood noodles",
    price: "2.29",
    description: "20 Bowls available",
  },
  {
    id: 10,
    img: Img1,
    title: "Spicy seasoned seafood noodles",
    price: "2.29",
    description: "20 Bowls available",
  },
  {
    id: 11,
    img: Img1,
    title: "Spicy seasoned seafood noodles",
    price: "2.29",
    description: "20 Bowls available",
  },
];
